@deployedBaseUrl = https://phonebook-backend-a96k.onrender.com

### Create user
POST {{deployedBaseUrl}}/api/users
Content-Type: application/json

{
  "username": "123",
  "name": "123",
  "phoneNumber": "9000000001",
  "password": "thisisshrikrishna@RADHA100"
}
### Login
POST {{deployedBaseUrl}}/api/login
Content-Type: application/json

{
  "identifier": "123",
  "password": "thisisshrikrishna@RADHA100"
}

 @token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjM5ZjllY2EwLTc2OWMtNGM1ZS1hMzg2LTg2MjEwNzQ2YTZhYiIsInVzZXJuYW1lIjoiMTIzIiwiaWF0IjoxNzgyODI1NzUzLCJleHAiOjE3ODI4NTQ1NTN9.rEvIpu52GXVPd78kU3ESjgfDInNO5zYxvtxj1O2jYWY

### Get persons
GET {{deployedBaseUrl}}/api/persons
Authorization: Bearer {{token}}


### Create person
POST {{deployedBaseUrl}}/api/persons
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Grace Hopper",
  "number": "123-456789"
}

@baseUrl = https://phonebook-backend-a96k.onrender.com

### Login
POST {{baseUrl}}/api/login
Content-Type: application/json

{
  "identifier": "123",
  "password": "thisisshrikrishna@RADHA100"
}