GET http://localhost:3001/api/notes

###

GET http://localhost:3001/api/notes/1

###

POST http://localhost:3001/api/notes
Content-Type: application/json

{
  "content": "REST-client is the best way to test the backend",
  "important":true
}

###

DELETE http://localhost:3001/api/notes/1